# netpyne Dockerfile

FROM jupyter/minimal-notebook

# necessary for TVB core:

ENV LANG=C.UTF-8

USER root
RUN apt-get update; apt-get install -y build-essential cmake git vim octave wget  \
                            libltdl7-dev libreadline6-dev libncurses5-dev libgsl0-dev openmpi-bin libopenmpi-dev \
                            zip unzip; \
    apt-get clean

USER $NB_UID
RUN mkdir -m777 $HOME/packages

# necessary python packages:
RUN conda create  -y --name dev setuptools cython h5py python=3.9
RUN conda install -y --name dev pandas pytest pytest-cov pytest-benchmark sqlalchemy
RUN conda install -y --name dev numba matplotlib
RUN /opt/conda/envs/dev/bin/pip install --upgrade pip
RUN /opt/conda/envs/dev/bin/pip install xarray oct2py elephant dill scikit-learn scipy

# TVB:
RUN git clone --depth 1 --branch master https://github.com/the-virtual-brain/tvb-root.git
RUN cd tvb-root; \
    git pull;\
    cd tvb_library; \
    /opt/conda/envs/dev/bin/python setup.py develop; \
    cd ../tvb_framework; \
    /opt/conda/envs/dev/bin/python setup.py develop; \
    cd ../tvb_contrib; \
    /opt/conda/envs/dev/bin/python setup.py develop;

RUN git clone --depth 1 https://github.com/mariomulansky/PySpike.git; \
    cd PySpike; \
    /opt/conda/envs/dev/bin/python setup.py build_ext install

# TVB NetPyNE:
RUN /opt/conda/envs/env_nest/bin/pip install neuron optuna
RUN git clone --depth 1 --branch dev https://github.com/Neurosim-lab/netpyne.git; \
    cd netpyne; \
    /opt/conda/envs/env_nest/bin/pip install -e .

RUN git clone --depth 1 --branch master https://github.com/the-virtual-brain/tvb-multiscale.git
RUN cd tvb-multiscale; \
    git pull; \
    /opt/conda/envs/env_nest/bin/python setup.py develop --no-deps;

#TODO: WIP Dockerfile-netpyne; check tvb_multiscale setup.py (INSTALL requirements?)